version: '3.8'

services:
  app:
    build: .
    container_name: muddibuddi
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - OPENWEATHER_BASE_URL=${OPENWEATHER_BASE_URL}
      - GEOCODING_URL=${GEOCODING_URL}
      - NODE_ENV=development
      - PORT=8000
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:17-alpine
    container_name: muddibuddi-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=muddibuddi
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
