### register user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username" : "test",
    "email" : "test@gmail.com",
    "password" : "123123123"
    "city" : "london"
    "state" : "UK"
}

### login user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email" : "test@gmail.com",
    "password" : "123123123"
}

# =====================================================

### get mood entries
GET http://localhost:8000/mood/entries
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtN2NxcGRvcDAwMDAwamlnMXRseTY1d3UiLCJpYXQiOjE3NDAwNjkxODksImV4cCI6MTc0MDE1NTU4OX0.S8OWc4H2AFSphjcCZ4n-7G9Pjwmw-BGonYDXh5qsqBI

### post mood entries
POST http://localhost:8000/mood/entries
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtN2NxcGRvcDAwMDAwamlnMXRseTY1d3UiLCJpYXQiOjE3NDAwNjkxODksImV4cCI6MTc0MDE1NTU4OX0.S8OWc4H2AFSphjcCZ4n-7G9Pjwmw-BGonYDXh5qsqBI
Content-Type: application/json

{
    "moodText" : "I bumped unto an old friend this evening, we caught up and I loved it",
    "entryDateTime" : "2025-02-15T14:48:00.000Z"
}
