### register user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username" : "test",
    "email" : "test@gmail.com",
    "password" : "123123123",
    "city" : "london",
    "country" : "UK"
}

### login user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email" : "test@gmail.com",
    "password" : "123123123"
}

### get user data
GET http://localhost:8000/user/data

# =====================================================

### get mood entries
GET http://localhost:8000/mood/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtN2R2eDhhbjAwMDBubDBvZGtvbnMyMnMiLCJpYXQiOjE3NDEwOTI0NjcsImV4cCI6MTc0MTE3ODg2N30.BSK8mDEMDpXDtInoKkynK7mvSlXgaLnLTgi2vIQ2TkA 

### post mood entries
POST http://localhost:8000/mood/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtN2R2eDhhbjAwMDBubDBvZGtvbnMyMnMiLCJpYXQiOjE3NDEwOTI0NjcsImV4cCI6MTc0MTE3ODg2N30.BSK8mDEMDpXDtInoKkynK7mvSlXgaLnLTgi2vIQ2TkA 
Content-Type: application/json

{
    "moodText" : "The weather has been ust good.",
    "entryDateTime" : "2025-03-04T23:00:25.487Z"
}
