### register user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username" : "test",
    "email" : "test@gmail.com",
    "password" : "123123123",
    "city" : "london",
    "country" : "UK"
}

### login user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email" : "test@gmail.com",
    "password" : "123123123"
}

# =====================================================

### get mood entries
GET http://localhost:8000/mood/entries
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtN2R0d3pzcjAwMDAwanVnMXU4ZGxkZTIiLCJpYXQiOjE3NDAwODU0MTcsImV4cCI6MTc0MDE3MTgxN30.FN7d5zL84E7uuMPxw8FenO77KoFdvFPCDtR4OGoMixI 

### post mood entries
POST http://localhost:8000/mood/entries
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtN2R0d3pzcjAwMDAwanVnMXU4ZGxkZTIiLCJpYXQiOjE3NDAwODU0MTcsImV4cCI6MTc0MDE3MTgxN30.FN7d5zL84E7uuMPxw8FenO77KoFdvFPCDtR4OGoMixI 
Content-Type: application/json

{
    "moodText" : "I bumped unto an old friend this evening, we caught up and I loved it",
    "entryDateTime" : "2025-02-15T14:48:00.000Z"
}
